import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('macOS team installer starts the console first and lets the user choose a model connection', async () => {
  const build = await readFile(new URL('../scripts/build-macos-installer.mjs', import.meta.url), 'utf8');
  const launcher = await readFile(new URL('../scripts/macos-launcher.m', import.meta.url), 'utf8');
  assert.match(build, /refoundation[\s\S]*start-console\.mjs/u);
  assert.match(build, /restrict-kordoc-bin\.mjs/u);
  assert.match(build, /node-arm64/u);
  assert.match(build, /node-x64/u);
  assert.match(build, /buildFileActivityHelper/u);
  assert.match(build, /t5-macos-file-activity/u);
  assert.match(build, /CoreServices/u);
  assert.match(build, /File activity helper is not universal/u);
  assert.match(build, /buildCoarseAppActivityHelper/u);assert.match(build,/t5-macos-coarse-app-activity/u);
  assert.match(build,/Coarse app activity helper is not universal/u);
  assert.match(build, /buildAppIcon/u);
  assert.match(build, /iconutil/u);
  assert.match(build, /CFBundleIconFile<\/key><string>GPAO-T5\.icns/u);
  assert.match(build, /COPYRIGHT/u);
  assert.match(build, /THIRD_PARTY_NOTICES\.md/u);
  assert.match(build, /'skill-packages'/u);
  assert.match(build, /'capabilities'/u);
  assert.match(build, /PACKAGE_SOURCE_PATHS/u);
  assert.match(build, /'status', '--porcelain', '--', ...PACKAGE_SOURCE_PATHS/u);
  assert.match(build, /sourceScope: 'packaged-inputs'/u);
  assert.match(build, /pkg-scripts[\s\S]*preinstall[\s\S]*stop-local-runtime\.mjs[\s\S]*product_update/u);
  assert.match(build, /\[ -f "\$OLD_PORT" \][\s\S]*"\$OLD_STOP"/u);
  assert.match(build, /assertProductionMacPayload/u);
  assert.match(build, /requireNewArtifact\(output\)/u);
  assert.match(build, /pkgutil[\s\S]*--check-signature[\s\S]*Developer ID Installer/u);
  assert.match(build, /do shell script[\s\S]*with administrator privileges/u);
  assert.match(build, /pkgutil --forget/u);
  assert.doesNotMatch(build, /ADMIN_COMMAND=/u);
  assert.doesNotMatch(build, /set -e\nrm -rf/u);
  assert.doesNotMatch(build, /gpao-t-handoff|AuthKey_|signing-private/u);
  assert.match(launcher, /ensure-local-runtime\.mjs/u);
  assert.match(launcher, /backgroundRuntimeMode/u);
  assert.match(launcher, /NSApplicationActivationPolicyProhibited/u);
  assert.match(launcher, /openConsoleWithCompletion:nil/u);
  assert.match(launcher, /--reason"\s*,\s*@"user_full_stop/u);
  assert.doesNotMatch(launcher, /user_quit/u);
  assert.doesNotMatch(launcher, /applicationWillTerminate[\s\S]*\[self\.child terminate\]/u);
  assert.doesNotMatch(launcher, /connect-chatgpt\.mjs|startOAuth/u);
  assert.match(launcher, /applicationDidFinishLaunching[\s\S]*?\[self startConsole\]/u);
  assert.match(launcher, /T5_REFOUNDATION_MODEL_CONNECTION_FILE/u);
  assert.match(launcher, /runtime\/bin/u);
  assert.doesNotMatch(launcher, /bin\/gpao-t5\.mjs/u);
  assert.match(build, /Contents\/MacOS\/\$\{product\.name\}/u);
  assert.match(build, /--background-runtime/u);
  assert.doesNotMatch(build, /<string>\/Applications\/\$\{product\.name\}\.app\/Contents\/Resources\/runtime\/bin\/node<\/string>[\s\S]*ensure-local-runtime/u);
  const verifier = await readFile(new URL('../scripts/verify-macos-installer.mjs', import.meta.url), 'utf8');
  assert.match(verifier, /const childExit = new Promise/u);
  assert.match(verifier, /mkdir\(home, \{ recursive: true \}\)/u);
  assert.match(verifier, /GPAO-T5\.icns/u);
  assert.match(verifier, /packaged application icon is not declared/u);
  assert.doesNotMatch(verifier, /child\.kill\('SIGTERM'\);\s*await new Promise\(\(resolveExit\) => child\.once/u);
  assert.match(verifier, /\^-----BEGIN \(RSA \|OPENSSH \)\?PRIVATE KEY-----\$/u);
  assert.doesNotMatch(verifier, /'-l', 'BEGIN \(RSA \)\?PRIVATE KEY/u);
});

test('6차 macOS package는 사용자 표시 6.0·내부 6.0.0을 분리하고 Windows package는 다음 Gate까지 유지한다', async () => {
  const packageMetadata = JSON.parse(await readFile(new URL('../../package.json', import.meta.url), 'utf8'));
  const build = await readFile(new URL('../scripts/build-macos-installer.mjs', import.meta.url), 'utf8');
  const windowsBuild = await readFile(new URL('../scripts/build-windows-package.mjs', import.meta.url), 'utf8');
  assert.equal(packageMetadata.version, '6.0.0');
  assert.match(build, /version:\s*'6\.0\.0'/u);
  assert.match(build, /displayVersion:\s*'6\.0'/u);
  assert.match(build, /CFBundleShortVersionString<\/key><string>\$\{product\.displayVersion\}/u);
  assert.match(build, /CFBundleVersion<\/key><string>\$\{product\.version\}/u);
  assert.match(windowsBuild, /version\s*=\s*'0\.3\.1'/u);
});
